baseURL = 'https://aitorquinza.github.io'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'Aitor Quinza Garcia'
theme = 'hugo-coder'
paginate = 20
enableEmoji = true

[markup.highlight]
style = "github-dark"

[params]
#author = "Aitor Quinza"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Aitor Quinza's personal website"
keywords = "blog,developer,personal"
info = ["Backend and DevOps Engineer"]
avatarURL = "images/avatar.png"
dateFormat = "January 2, 2006"
since = 1996
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/aitorquinza/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/aitorquinza/"


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"


[languages.es-es]
languageName = ":es:"
title = "Aitor Quinza Garcia"

[languages.es-es.params]
info = ["Ingeniero Backend y DevOps"]
description = "Página web de Aitor Quinza"
keywords = "blog,developer,personal"

[[languages.es-es.menu.main]]
name = "Sobre Mí"
weight = 1
url = "about/"

[[languages.es-es.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.es-es.menu.main]]
name = "Proyectos"
weight = 3
url = "projects/"

